import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#161214",
        "on-secondary-fixed-variant": "#374b3d",
        secondary: "#b5ccb9",
        "on-tertiary-container": "#005367",
        "tertiary-container": "#00cdfa",
        "surface-container-high": "#2d292a",
        "on-primary-container": "#694053",
        "surface-bright": "#3d3839",
        "on-tertiary": "#003543",
        "surface-container": "#231e20",
        "on-primary-fixed": "#311021",
        "primary-fixed-dim": "#eeb7cf",
        "surface-variant": "#383335",
        "on-surface-variant": "#d3c2c7",
        surface: "#161214",
        "secondary-container": "#3a4e3f",
        "secondary-fixed": "#d1e8d5",
        "primary-container": "#e4aec5",
        "inverse-surface": "#eae0e2",
        outline: "#9c8d92",
        "on-primary-fixed-variant": "#633a4e",
        "on-secondary": "#213527",
        "surface-container-lowest": "#110d0f",
        "surface-container-highest": "#383335",
        "surface-dim": "#161214",
        "on-background": "#eae0e2",
        primary: "#ffcae0",
        "secondary-fixed-dim": "#b5ccb9",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#a8beac",
        "on-secondary-fixed": "#0c1f13",
        "tertiary-fixed": "#b7eaff",
        "tertiary-fixed-dim": "#4cd6ff",
        "on-tertiary-fixed-variant": "#004e60",
        "outline-variant": "#4f4448",
        "surface-container-low": "#1f1a1c",
        "inverse-on-surface": "#342f31",
        "on-error": "#690005",
        "inverse-primary": "#7d5165",
        "on-tertiary-fixed": "#001f28",
        "on-surface": "#eae0e2",
        "error-container": "#93000a",
        tertiary: "#98e3ff",
        "primary-fixed": "#ffd8e7",
        "surface-tint": "#eeb7cf",
        "on-primary": "#492437",
        error: "#ffb4ab",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        headline: ["Anybody", "sans-serif"],
        body: ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
